[Feat] isbn으로 api에서 책 정보 불러와 상세 페이지 구성
alexcho617/BookfelTower pull request #30
Opened 2023-06-03 07:33 UTC by haram22

**🍎 Issue Number**
Close #29 
<br>

**🍏 작업 내역**
검색 결과에서 isbn으로 api 정보 불러와서 화면 구성하기
<br>

**🛠️ 작업 유형**

- [X] Feature 신규 기능 추가
<br>

**📜 체크리스트**
- [ ] Merge 하는 브랜치가 올바른가?
- [ ] 코딩컨벤션을 준수하는가?
- [ ] PR과 관련없는 변경사항이 없는가?
- [ ] 내 코드에 대한 자기 검토가 되었는가?
<br>

**⚠️ PR 특이 사항**
모듈화를 어느정도까지 해야 할지 잘 모르겠어요...!
4번정도 반복되는 텍스트 스타일이 있다면, 모듈화 하여 두는 것이 좋을까요?
<br>

**🖼️ 결과물 사진**

<img width="255" alt="스크린샷 2023-06-03 오후 4 32 05" src="https://github.com/alexcho617/BookfelTower/assets/97924765/cddb39b2-a708-4b63-9487-1dec6d0a1048"><img width="255" alt="스크린샷 2023-06-03 오후 4 32 09" src="https://github.com/alexcho617/BookfelTower/assets/97924765/20eb2030-e98b-485a-bbc4-7161e125667f">

2023-06-04 07:26 UTC, alexcho617 commented on BookfelTower/BookfelTower/Home/DetailPage/SampleDetailView.swift
> +    func LookUp(isbn: String) {
함수 이름 시작은 소문자로 해주세요 :)

2023-06-04 07:28 UTC, alexcho617 commented on BookfelTower/BookfelTower/Home/SearchPage/SearchPageView.swift
> +        NavigationLink(destination: SampleDetailView(isbn: self.isbn)){
SampleDetailView는 제가 네비게이션 테스트 한다고 썼던거라 DetailPageView에다가 작업 해주시는게 맞았는데 오해가 있었나봐요!

2023-06-04 07:30 UTC, alexcho617 requested changes
-SampleDetailView 사용하지 말아주세요
-DetailPageView에다가 작업해주세요
-함수명 camelCase로 부탁드립니다 👍 

text style 모듈화에 관해서는 하람님이 필요하다고 느끼셨으니 지금 해도 좋을것 같아요!
어차피 나중에 디자인 입힐때도 모듈화가 되어있어야 편하니까요 :)

2023-06-06 15:39 UTC, haram22 commented
> -SampleDetailView 사용하지 말아주세요 -DetailPageView에다가 작업해주세요 -함수명 camelCase로 부탁드립니다 👍
> 
> text style 모듈화에 관해서는 하람님이 필요하다고 느끼셨으니 지금 해도 좋을것 같아요! 어차피 나중에 디자인 입힐때도 모듈화가 되어있어야 편하니까요 :)

기존 디테일 페이지와 다른 부분이 있어 다른 파일에서 하는 것이 나을 것 같아 그대로 진행했습니다.
detail Page는 사용자가 서재에 담은 책에 대한 detail page로, 서치를 통해 찾은 디테일 페이지와는 다른 부분이 있는데, 어떻게 하는게 좋을까요?
1. 따로 searchDetailPage를 만든다.
2. detail page에서 모듈화 하여 상태에 따라 다르게 보여준다.

뭐가 더 나을까요? 의견 주세요 !

2023-06-07 04:28 UTC, merged